const cars = [
    {
      itemName: "Toyota Corolla",
      description: "Reliable and fuel-efficient compact car.",
      imageUrl: "https://i.ytimg.com/vi/7NaMvb-4yyk/maxresdefault.jpg",
      model: "2022",
      availability: "In",
      transmission: "Automatic",
      exterior: "Silver",
      fuel: "Gasoline",
      drive: "Front-Wheel Drive",
    },
    {
      itemName: "Honda Civic",
      description: "Popular and well-rounded compact car.",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDHhqKFhmRuocXQNZFlufo_qXIu_M45BmNXPh4TDYBsQ&s",
      model: "2022",
      availability: "In",
      transmission: "Automatic",
      exterior: "White",
      fuel: "Gasoline",
      drive: "Front-Wheel Drive",
    },
    {
      itemName: "Ford Mustang",
      description: "Iconic and powerful sports car.",
      imageUrl: "https://i.ytimg.com/vi/8qS3Udpu97Q/maxresdefault.jpg",
      model: "2023",
      availability: "In",
      transmission: "Manual",
      exterior: "Red",
      fuel: "Gasoline",
      drive: "Rear-Wheel Drive",
    },
    {
      itemName: "Tesla Model 3",
      description: "Electric luxury sedan with impressive range.",
      imageUrl: "https://tesbros.com/cdn/shop/products/IMG_3284_c78dd8f1-c26e-488e-978e-a0956487f627_1200x.jpg?v=1658889483",
      model: "2022",
      availability: "In",
      transmission: "Automatic",
      exterior: "Black",
      fuel: "Electric",
      drive: "All-Wheel Drive",
    },
    {
      itemName: "BMW X5",
      description: "Luxurious and spacious SUV.",
      imageUrl: "https://www.carscoops.com/wp-content/uploads/2020/01/2020-bmw-x5-40i-msport-pythonic-blue-33.jpg",
      model: "2022",
      availability: "Out",
      transmission: "Automatic",
      exterior: "Blue",
      fuel: "Gasoline",
      drive: "All-Wheel Drive",
    },
    {
      itemName: "Audi A4",
      description: "Sophisticated and comfortable luxury sedan.",
      imageUrl: "https://images.carexpert.com.au/resize/3000/-/app/uploads/2020/11/2021-Audi-A4-45-TFSI-quattro-S-line-Sedan-2020-Audi-A4-S-Line-16.jpg",
      model: "2022",
      availability: "In",
      transmission: "Automatic",
      exterior: "Gray",
      fuel: "Gasoline",
      drive: "All-Wheel Drive",
    },
    {
      itemName: "Jeep Wrangler",
      description: "Iconic off-road SUV with removable doors.",
      imageUrl: "https://imgd.aeplcdn.com/370x208/n/sceo43a_1589945.jpg?q=75",
      model: "2023",
      availability: "In",
      transmission: "Automatic",
      exterior: "Green",
      fuel: "Gasoline",
      drive: "Four-Wheel Drive",
    },
    {
      itemName: "Hyundai Kona",
      description: "Compact SUV with a sporty design.",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSw0W_GvSNjZiBYVBjdbH_Twn25Cr3XBDApVT_Ylcoj&s",
      model: "2022",
      availability: "In",
      transmission: "Automatic",
      exterior: "Orange",
      fuel: "Gasoline",
      drive: "Front-Wheel Drive",
    },
    {
      itemName: "Volvo XC90",
      description: "Elegant and safe luxury SUV.",
      imageUrl: "https://www.motortrend.com/uploads/sites/5/2020/06/2020-Volvo-XC90-T8-E-AWD-Inscription-30.jpg?fit=around%7C875:492",
      model: "2022",
      availability: "Out",
      transmission: "Automatic",
      exterior: "White",
      fuel: "Gasoline",
      drive: "All-Wheel Drive",
    },
    {
      itemName: "Chevrolet Camaro",
      description: "Muscle car with a powerful V8 engine.",
      imageUrl: "https://media.istockphoto.com/id/1307367508/photo/chevrolet-camaro-v.jpg?s=612x612&w=0&k=20&c=lM9Wpiz4TUSXmZH5USwh5iFR-9pP6M4tazUr-0SipzQ=",
      model: "2023",
      availability: "In",
      transmission: "Manual",
      exterior: "Yellow",
      fuel: "Gasoline",
      drive: "Rear-Wheel Drive",
    },
  ];
  export default cars;
  
 
  