const users = [
    {
      name: "John Doe",
      email: "john.doe@example.com",
      phoneNumber: "+254712345678",
      passcode: "password123",
      address: "123 Main Street",
      county: "Nairobi",
      town: "Nairobi",
    },
    {
      name: "Jane Smith",
      email: "jane.smith@example.com",
      phoneNumber: "+254723456789",
      passcode: "secure123",
      address: "456 Park Avenue",
      county: "Mombasa",
      town: "Mombasa",
    },
    {
      name: "David Johnson",
      email: "david.johnson@example.com",
      phoneNumber: "+254734567890",
      passcode: "secret123",
      address: "789 Elm Street",
      county: "Kisumu",
      town: "Kisumu",
    },
    // Add more users here...
    {
      name: "Sarah Williams",
      email: "sarah.williams@example.com",
      phoneNumber: "+254745678901",
      passcode: "pass123",
      address: "10 Lake View Drive",
      county: "Nakuru",
      town: "Nakuru",
    },
    {
      name: "Michael Brown",
      email: "michael.brown@example.com",
      phoneNumber: "+254756789012",
      passcode: "secure456",
      address: "33 Oak Street",
      county: "Eldoret",
      town: "Eldoret",
    },
    {
      name: "Linda Davis",
      email: "linda.davis@example.com",
      phoneNumber: "+254767890123",
      passcode: "123456",
      address: "22 Maple Avenue",
      county: "Thika",
      town: "Thika",
    },
    {
      name: "William Wilson",
      email: "william.wilson@example.com",
      phoneNumber: "+254778901234",
      passcode: "pass789",
      address: "55 Pine Road",
      county: "Kisii",
      town: "Kisii",
    },
    {
      name: "Emily Miller",
      email: "emily.miller@example.com",
      phoneNumber: "+254789012345",
      passcode: "secure789",
      address: "99 Cedar Lane",
      county: "Nyeri",
      town: "Nyeri",
    },
    {
      name: "James Anderson",
      email: "james.anderson@example.com",
      phoneNumber: "+254790123456",
      passcode: "123pass",
      address: "44 Birch Street",
      county: "Kitale",
      town: "Kitale",
    },
    {
      name: "Olivia Martinez",
      email: "olivia.martinez@example.com",
      phoneNumber: "+254701234567",
      passcode: "password789",
      address: "66 Willow Avenue",
      county: "Naivasha",
      town: "Naivasha",
    },
  ];
  
  export default users;
  